Throw S3FileStorageException when something goes wrong and response is not as expected.
FoundatioFx/Foundatio.AWS pull request #305
Opened 2022-11-07 09:02 UTC by frabe1579

This PR changes GetFileStreamAsync, GetFileInfoAsync, and ExistsAsync.
The changes test for precise response status code, in order to avoid silent catching of particular S3 errors.
All tests passes, but not new tests were added because of the difficult to simulate errors. A classic error simulation is network error, but this already throws other exceptions.

2022-11-07 09:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FoundatioFx/Foundatio.AWS?pullRequest=305) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FoundatioFx/Foundatio.AWS?pullRequest=305) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FoundatioFx/Foundatio.AWS?pullRequest=305) it.</sub>

2022-11-07 14:24 UTC, frabe1579 commented
There is a failure on Queue tests, but this PR touches only FileStorage, maybe future merges can solve this.

2022-11-07 14:58 UTC, niemyjski reviewed
@ejsmith I wonder if we should also be adding debug / trace logging around responses / before we throw.

2022-11-07 14:58 UTC, niemyjski commented on src/Foundatio.AWS/Storage/S3FileStorage.cs
> +                    throw new S3FileStorageException($"Invalid status code, expected 200 OK, found {(int)res.HttpStatusCode} {res.HttpStatusCode}.");
```suggestion
                    throw new S3FileStorageException($"Invalid status code {res.HttpStatusCode} ({(int)res.HttpStatusCode}): Expected 200 OK");
```

2022-11-07 14:58 UTC, niemyjski commented on src/Foundatio.AWS/Storage/S3FileStorage.cs
>              }
Would be nice to use exception filters here

2022-11-30 16:07 UTC, ejsmith requested changes
Wow. Just realized that I reviewed this a long while back and didn't submit the review. Sorry.

2022-11-30 16:07 UTC, ejsmith commented on src/Foundatio.AWS/Storage/S3FileStorageException.cs
> +namespace Foundatio.AWS.Storage {
We definitely don't want to have exceptions that are unique to each implementation where a user would need to check for different kinds of exceptions depending on which implementation they are using.

2022-11-30 16:07 UTC, ejsmith commented on src/Foundatio.AWS/Storage/S3FileStorage.cs
> +            if (res.HttpStatusCode != System.Net.HttpStatusCode.OK)
We are probably going to want to think about some sort of retry mechanism for things that can be retried. I guess it doesn't need to be part of this change though.

2025-05-01 14:56 UTC, niemyjski commented
@frabe1579 could you please address Erics comments, would love to get this merged.

2025-05-13 16:09 UTC, ejsmith commented on src/Foundatio.AWS/Storage/S3FileStorageException.cs
> +namespace Foundatio.AWS.Storage {
@frabe1579 I think this was the main concern with merging this PR. We don't want to have different exceptions being thrown per implementation.

2025-05-13 16:25 UTC, frabe1579 commented on src/Foundatio.AWS/Storage/S3FileStorageException.cs
> +namespace Foundatio.AWS.Storage {
Sorry I'm not comfortable with branches and pull-requests. I've removed S3FileStorageException and corrected code. Can you see it?

2025-05-14 13:13 UTC, niemyjski commented on src/Foundatio.AWS/Storage/S3FileStorageException.cs
> +namespace Foundatio.AWS.Storage {
Yes, thank you, we can delete this file.

2025-05-15 02:16 UTC, niemyjski commented on src/Foundatio.AWS/Storage/S3FileStorageException.cs
> +namespace Foundatio.AWS.Storage {
I'm going to work towards merging this pr then create a StorageException in the core library and update the core implementations and then update this line (post merge) to use this new exception type.

2025-05-20 20:10 UTC, niemyjski commented on src/Foundatio.AWS/Storage/S3FileStorageException.cs
> +namespace Foundatio.AWS.Storage {
https://github.com/FoundatioFx/Foundatio/pull/385

2025-05-29 21:53 UTC, merged